#!/bin/sh

export PATH=/usr/bin

start()
{
    exportfs -r
    rpc.nfsd -s
}

stop()
{
    rpc.nfsd 0
    exportfs -au
    exportfs -f
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
esac
