#!/bin/sh

echo "Running kernel.d scripts..."

find -L /etc/kernel.d /usr/lib/kernel.d -maxdepth 1 -not -type d 2>/dev/null | \
  sed 's,.*/\(.*\),& \1,' | sort -k2 -s | uniq -f1 | cut -d' ' -f1 | \
  while read hook; do
    if [ -x "$hook" ]; then
        /bin/sh "$hook"
    else
        "$hook"
    fi
    [ $? -eq 0 ] || echo "FAILED: $hook"
done
