#!/bin/sh

cd /usr/libexec/base-kernel

. ./script-funcs

KVER=$(get_kernver "$1" "$2")

./kernel-clean-initramfs "$KVER"

# clean up copied apk-dist
for modf in /usr/lib/modules/$KVER/modules.*; do
    [ -f "$modf" ] || continue
    rm -f $modf
done
