#!/bin/sh

cd /usr/libexec/base-kernel

. ./script-funcs

KVER_NEW=$(get_kernver "$1" "$3")
KVER_OLD=$(get_kernver "$2" "$3")

if [ "$KVER_OLD" != "$KVER_NEW" ]; then
    ./kernel-post-upgrade "$KVER_OLD"
fi

copy_modfiles "$KVER_NEW"
