commit c19af3ea3a649e043d43db18c3e2815746d94022
Author: q66 <q66@chimera-linux.org>
Date:   Wed Sep 13 20:56:12 2023 +0200

    makefile portability

diff --git a/Makefile b/Makefile
index c77c0c5..f4da429 100644
--- a/Makefile
+++ b/Makefile
@@ -147,16 +147,20 @@ cmd_version.o : .version
 install: INITRAMFS_HOOK=$(INITRAMFS_DIR)/hooks/bcachefs
 install: INITRAMFS_SCRIPT=$(INITRAMFS_DIR)/scripts/local-premount/bcachefs
 install: bcachefs
-	$(INSTALL) -m0755 -D bcachefs      -t $(DESTDIR)$(ROOT_SBINDIR)
+	$(INSTALL) -d $(DESTDIR)$(ROOT_SBINDIR)
+	$(INSTALL) -d $(DESTDIR)$(PREFIX)/share/man/man8
+	$(INSTALL) -d $(DESTDIR)$(INITRAMFS_DIR)/scripts/local-premount
+	$(INSTALL) -d $(DESTDIR)$(INITRAMFS_DIR)/hooks
+	$(INSTALL) -m0755    bcachefs         $(DESTDIR)$(ROOT_SBINDIR)
 	$(INSTALL) -m0755    fsck.bcachefs    $(DESTDIR)$(ROOT_SBINDIR)
 	$(INSTALL) -m0755    mkfs.bcachefs    $(DESTDIR)$(ROOT_SBINDIR)
 	$(INSTALL) -m0755    mount.bcachefs   $(DESTDIR)$(ROOT_SBINDIR)
-	$(INSTALL) -m0644 -D bcachefs.8    -t $(DESTDIR)$(PREFIX)/share/man/man8/
-	$(INSTALL) -m0755 -D initramfs/script $(DESTDIR)$(INITRAMFS_SCRIPT)
-	$(INSTALL) -m0755 -D initramfs/hook   $(DESTDIR)$(INITRAMFS_HOOK)
+	$(INSTALL) -m0644    bcachefs.8       $(DESTDIR)$(PREFIX)/share/man/man8/
+	$(INSTALL) -m0755    initramfs/script $(DESTDIR)$(INITRAMFS_SCRIPT)
+	$(INSTALL) -m0755    initramfs/hook   $(DESTDIR)$(INITRAMFS_HOOK)
 
-	sed -i '/^# Note: make install replaces/,$$d' $(DESTDIR)$(INITRAMFS_HOOK)
-	echo "copy_exec $(ROOT_SBINDIR)/bcachefs /sbin/bcachefs" >> $(DESTDIR)$(INITRAMFS_HOOK)
+	sed -i '' '/^# Note: make install replaces/,$$d' $(DESTDIR)$(INITRAMFS_HOOK)
+	echo "copy_exec $(ROOT_SBINDIR)/bcachefs /usr/bin/bcachefs" >> $(DESTDIR)$(INITRAMFS_HOOK)
 
 .PHONY: clean
 clean:
