pkgname = "pv"
pkgver = "1.9.15"
pkgrel = 0
build_style = "gnu_configure"
hostmakedepends = ["automake", "gettext-devel"]
pkgdesc = "Tool for monitoring the progress of data through a pipeline"
maintainer = "Erica Z <zerica@callcc.eu>"
license = "GPL-3.0-or-later"
url = "https://www.ivarch.com/programs/pv.shtml"
source = f"https://www.ivarch.com/programs/sources/pv-{pkgver}.tar.gz"
sha256 = "e2b17564ab9eba1ec2caae285960cbf363b4401dffda191a60a0befe68e17dac"
