pkgname = "gnome-video-effects"
pkgver = "0.6.0"
pkgrel = 0
build_style = "meson"
hostmakedepends = ["meson", "pkgconf", "gettext"]
makedepends = ["gstreamer-devel"]
pkgdesc = "Collection of GStreamer effects for GNOME"
license = "GPL-2.0-or-later"
url = "https://gitlab.gnome.org/GNOME/gnome-video-effects"
source = f"$(GNOME_SITE)/gnome-video-effects/{pkgver[:-2]}/gnome-video-effects-{pkgver}.tar.xz"
sha256 = "d7aeaeb46b3f5a832fb2e0d90b42bf8c6160202ca52ac9add17afce192e3c8a8"
