#!/usr/bin/env python3

import os
import sys
import shutil

# we need structural pattern matching in templates and cbuild itself
if sys.version_info < (3, 10):
    sys.exit("Python 3.10 or newer is required")

# required programs in the system
for prog in ["bwrap", "openssl", "apk", "git", "tee"]:
    if not shutil.which(prog):
        sys.exit(f"Required program not found: {prog}")

# running as root interferes with the sandbox functionality
if os.geteuid() == 0:
    sys.exit("Please don't run cbuild as root")

from src import runner

runner.fire()
