# Prepare upsd and upsmon environment

# the following config files contain passwords in plain text
# permissions adjusted so they are reabable services running as _nut
# upsmon.conf also configures a command to be run as root to poweroff

z /etc/ups/upsd.users 0640 root _nut - -
z /etc/ups/upsmon.conf 0640 root _nut - -
