pkgname = "nix"
pkgver = "2.26.2"
pkgrel = 0
build_style = "meson"
configure_args = [
    # Use /usr/lib instead of /usr/libexec
    "--libexecdir=/usr/lib",
    # /nix/var is the default, but cbuild passes --localstatedir=/var.
    # usually this is correct, but we need nix stuff to be in /nix/var.
    "--localstatedir=/nix/var/",
    # profile-dir defaults to etc/profile.d which becomes
    # /usr/etc/profile.d with the prefix /usr. This is wrong,
    # we want these system files to go in /etc/profile.d.
    # Note that we now remove them anyways, because we have our own,
    # but it still felt cleaner to leave it like this.
    "-Dnix:profile-dir=/etc/profile.d",
    # Upstream nix prefers editline. Readline is an afterthought, so completion
    # and history don't work with readline. As libedit has a readline compatible
    # interface, history and completion won't work with libedit either. Patches
    # to be able to use libedit instead of readline are in `patches/`, but there
    # will be missing functionality, like with readline.
    "-Dlibcmd:readline-flavor=editline",
    # We need the below to fix "ERROR: clang does not know how to do prelinking.",
    # a.k.a. nix only supports shared libraries.
    "-Ddefault_library=shared",
    # We want man pages.
    "-Ddoc-gen=true",
    # We don't need the perl bindings (and don't have the dependencies to build it).
    "-Dbindings=false",
    # We don't do test as it requires network, so don't build them.
    "-Dunit-tests=false",
]
hostmakedepends = [
    "meson",
    "bison",
    "flex",
    "cmake",
    "pkgconf",
    "bash",
    # These are needed for the doc-gen target.
    "doxygen",
    "mdbook",
    # Preprocessor for mdbook that checks for broken links
    # The docs include a lot of things, but we only package the man pages.
    # man pages don't support links, so we don't care if they are dead or not.
    # "mdbook-linkcheck",
    "rsync",
    "jq",
]
makedepends = [
    "boost-devel",
    "openssl3-devel",
    "libarchive-devel",
    "libsodium-devel",
    "brotli-devel",
    "nlohmann-json",
    "curl-devel",
    "libseccomp-devel",
    "sqlite-devel",
    "gc-devel",
    "lowdown-devel",
    "libgit2-devel",
    "toml11",
    # Use editline as nix recommends, but readline or libedit also work.
    "editline-devel",
]
# We don't actually use these at the moment, because checks are disabled.
checkdepends = [
    "rapidcheck",  # not in cports yet
    "gtest-devel",
]
pkgdesc = "Purely functional package manager"
maintainer = "Mathijs Rietbergen <mathijs.rietbergen@proton.me>"
license = "LGPL-2.1-or-later"
url = "https://github.com/NixOS/nix"
source = f"{url}/archive/refs/tags/{pkgver}.tar.gz"
sha256 = "283ac42ec602e335ffd9c42721f35f1a20e8a7eb629ec5d9cc604a2fc2489ec0"
# With `int` enabled, all nix tools constantly fail with "Illegal instruction".
hardening = ["!int"]
# Checks require network to download from nixpkgs, but network is not available
# in check phase.
# Cross compiling fails as meson cannot find CMake when cross compiling.
# This seems like a generic issue, unrelated to nix...
options = ["!check", "!cross"]


def post_install(self):
    # Remove systemd files.
    self.uninstall("usr/lib/systemd")

    # Creating /nix/var/nix/daemon-socket/socket is unneeded as nix-daemon can
    # do it on its own, but the systemd unit files require the socket to be
    # present before starting (why? I have no clue).
    # That is why it exists upstream. We don't need this by any means.
    self.uninstall("usr/lib/tmpfiles.d")

    # We have our own, so we don't use these.
    self.uninstall("etc/profile.d")

    # Install the files that set up the environment, service and config.
    self.install_sysusers(
        self.files_path / "nix-daemon.sysusers.conf", name="nix-daemon"
    )
    self.install_sysusers(self.files_path / "nix.sysusers.conf", name="nix")
    self.install_service(
        self.files_path / "nix-daemon.dinit", name="nix-daemon"
    )
    self.install_file(self.files_path / "nix.conf", "etc/nix")
    self.install_file(
        self.files_path / "nix.defaults", "etc/default", name="nix"
    )
    self.install_file(
        self.files_path / "nix.profile.d", "etc/profile.d", name="nix.sh"
    )


@subpackage("nix-devel")
def _(self):
    return self.default_devel()


@subpackage("nix-devel-doc")
def _(self):
    # Contains the api documentation generated by doxygen, so should not be in nix-doc,
    # as it is mostly useful for development.
    return ["usr/share/doc/nix/internal-api", "usr/share/doc/nix/external-api"]
