diff -r 2f9ecf1445ea GNUmakefile
--- a/GNUmakefile	Tue May 30 09:08:17 2023 +0200
+++ b/GNUmakefile	Thu Apr 25 08:15:03 2024 +0100
@@ -3,10 +3,11 @@
 .INTERMEDIATE: lunbound.o
 
 LUA_VERSION = 5.2
-LUA_PC      = lua-$(LUA_VERSION)
+LUA_PC      = lua$(LUA_VERSION)
 LUA_LIBDIR  = $(shell pkg-config --variable=INSTALL_CMOD $(LUA_PC))
 
 CC          = c99
+LD			= $(CC)
 CFLAGS     += -fPIC $(shell pkg-config --cflags $(LUA_PC)) -Wall -Wextra -pedantic -ggdb
 LDLIBS     += -lunbound
 LDFLAGS    += -shared
