--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
-all install uninstall clean:
+all install uninstall clean test:
 	$(MAKE) -C tree-sitter-markdown $@
 	$(MAKE) -C tree-sitter-markdown-inline $@
 
-.PHONY: all install uninstall clean
+.PHONY: all install uninstall clean test

