pkgname = "brlaser"
pkgver = "6.2.8"
pkgrel = 0
build_style = "cmake"
hostmakedepends = ["cmake", "ninja"]
makedepends = ["cups-devel"]
pkgdesc = "CUPS driver for monochrome Brother laser printers"
license = "GPL-2.0-or-later"
url = "https://github.com/Owl-Maintain/brlaser"
source = f"{url}/archive/refs/tags/v{pkgver}.tar.gz"
sha256 = "16dae855aa7fff0eef0c05398fab37678243d7d610fa5f9af0d3a2cc9bf08cb0"
hardening = ["cfi", "vis"]
