pkgname = "base-man"
pkgver = "2.0"
pkgrel = 0
build_style = "meta"
depends = ["mandoc"]
pkgdesc = "Base package for manpages"
license = "custom:meta"
url = "https://chimera-linux.org"
options = ["empty"]
