pkgname = "bsdgzip"
version = "0.99.1"
revision = 0
bootstrap = True
build_style = "gnu_makefile"
hostmakedepends = ["pkgconf"]
makedepends = ["musl-fts-devel", "liblzma-devel", "zlib-devel", "bzip2-devel"]
short_desc = "The gzip(1) suite of utilities from FreeBSD"
maintainer = "q66 <q66@chimera-linux.org>"
license = "BSD-2-Clause"
homepage = "https://github.com/chimera-linux/bsdgzip"
distfiles = [f"https://github.com/chimera-linux/{pkgname}/archive/refs/tags/v{version}.tar.gz"]
checksum = ["9ea8712dfce8e0ac5713cee40ade52c71a339b53e672c0caa82a692a77569c57"]
