pkgname = "bsdgzip"
version = "0.99.0"
revision = 1
bootstrap = True
build_style = "gnu_makefile"
hostmakedepends = ["pkgconf"]
makedepends = ["musl-fts-devel", "liblzma-devel", "zlib-devel", "bzip2-devel"]
short_desc = "The gzip(1) suite of utilities from FreeBSD"
maintainer = "q66 <q66@chimera-linux.org>"
license = "BSD-2-Clause"
homepage = "https://github.com/chimera-linux/bsdgzip"
distfiles = [f"https://github.com/chimera-linux/{pkgname}/archive/refs/tags/v{version}.tar.gz"]
checksum = ["c0307abd0c94c6f664364f35d7e087c0da019f4cc70de5f84767ba38e398a78d"]
