diff --git a/Makefile b/Makefile
index fa032a5..0cca78a 100644
--- a/Makefile
+++ b/Makefile
@@ -26,10 +26,9 @@ clean:
 install: all
 	install -d $(DESTDIR)$(BIN_DIR)/
 	install -m0755 -t $(DESTDIR)$(BIN_DIR)/ $(BUILD_SCRIPTS)
-	install -dD $(DESTDIR)/etc
-	install -dD $(DESTDIR)$(PREFIX)/share/asahi-scripts
+	install -d $(DESTDIR)/etc
+	install -d $(DESTDIR)$(PREFIX)/share/asahi-scripts
 	install -m0644 -t $(DESTDIR)$(PREFIX)/share/asahi-scripts functions.sh
-	install -dD $(DESTDIR)/$(SYS_PREFIX)/lib/firmware/vendor
 
 install-mkinitcpio: install
 	install -dD $(DESTDIR)$(PREFIX)/lib/initcpio/install
@@ -48,8 +47,8 @@ install-dracut: install
 	install -m0755 -t $(DESTDIR)$(DRACUT_MODULES_DIR)/99asahi-firmware dracut/modules.d/99asahi-firmware/module-setup.sh
 
 install-macsmc-battery: install
-	install -dD $(DESTDIR)$(SYSTEMD_UNIT_DIR)
-	install -dD $(DESTDIR)$(UDEV_RULES_DIR)
+	install -d $(DESTDIR)$(SYSTEMD_UNIT_DIR)
+	install -d $(DESTDIR)$(UDEV_RULES_DIR)
 	install -m0755 -t $(DESTDIR)$(SYSTEMD_UNIT_DIR) macsmc-battery/systemd/macsmc-battery-charge-control-end-threshold.path
 	install -m0755 -t $(DESTDIR)$(SYSTEMD_UNIT_DIR) macsmc-battery/systemd/macsmc-battery-charge-control-end-threshold.service
 	install -m0644 -t $(DESTDIR)$(UDEV_RULES_DIR) macsmc-battery/udev/93-macsmc-battery-charge-control.rules
@@ -64,6 +63,8 @@ install-arch: install install-mkinitcpio install-macsmc-battery
 	install -dD $(DESTDIR)$(PREFIX)/share/libalpm/hooks
 	install -m0644 -t $(DESTDIR)$(PREFIX)/share/libalpm/hooks libalpm/hooks/95-m1n1-install.hook
 
+install-chimera: install install-initramfs install-macsmc-battery
+
 install-fedora: install install-dracut install-macsmc-battery
 
 uninstall:
