pkgname = "xdg-dbus-proxy"
pkgver = "0.1.3"
pkgrel = 0
build_style = "gnu_configure"
configure_args = ["--enable-man"]
hostmakedepends = ["pkgconf", "xsltproc", "docbook-xsl-nons"]
makedepends = ["libglib-devel"]
checkdepends = ["dbus"]
pkgdesc = "Filtering proxy for D-Bus connections"
maintainer = "q66 <q66@chimera-linux.org>"
license = "GPL-3.0-or-later"
url = "https://github.com/flatpak/xdg-dbus-proxy"
source = f"{url}/releases/download/{pkgver}/{pkgname}-{pkgver}.tar.xz"
sha256 = "03b5d28ca879253ddbbce31098909becca1495ea811a6377a492e28f16c09b9b"
