CBUILD_TARGET_CFLAGS = ["-march=armv8-a"]
CBUILD_TARGET_CXXFLAGS = list(CBUILD_TARGET_CFLAGS)
CBUILD_TARGET_FFLAGS = list(CBUILD_TARGET_CFLAGS)
CBUILD_TARGET_ENDIAN = "little"
CBUILD_TARGET_WORDSIZE = 64
CBUILD_TRIPLET = "aarch64-unknown-linux-musl"
