CBUILD_TARGET_CFLAGS = ["-mtune=power9"]
CBUILD_TARGET_CXXFLAGS = list(CBUILD_TARGET_CFLAGS)
CBUILD_TARGET_FFLAGS = list(CBUILD_TARGET_CFLAGS)
CBUILD_TARGET_ENDIAN = "little"
CBUILD_TARGET_WORDSIZE = 64
CBUILD_TARGET_HARDENING = ["scp"]
CBUILD_TRIPLET = "powerpc64le-unknown-linux-musl"
