CBUILD_TARGET_CFLAGS = []
CBUILD_TARGET_CXXFLAGS = list(CBUILD_TARGET_CFLAGS)
CBUILD_TARGET_FFLAGS = list(CBUILD_TARGET_CFLAGS)
CBUILD_TARGET_ENDIAN = "little"
CBUILD_TARGET_WORDSIZE = 64
CBUILD_TRIPLET = "x86_64-unknown-linux-musl"
