# distfile sites to be used from templates

sourceforge = "https://downloads.sourceforge.net/sourceforge"
freedesktop = "https://freedesktop.org/software"
mozilla = "https://ftp.mozilla.org/pub"
debian = "http://ftp.debian.org/debian/pool"
ubuntu = "http://archive.ubuntu.com/ubuntu/pool"
nongnu = "https://download.savannah.nongnu.org/releases"
kernel = "https://www.kernel.org/pub/linux"
gnome = "https://download.gnome.org/sources"
xorg = "https://www.x.org/releases/individual"
cpan = "https://www.cpan.org/modules/by-module"
pypi = "https://files.pythonhosted.org/packages/source"
gnu = "https://ftp.gnu.org/gnu"
kde = "https://download.kde.org/stable"
