pkgname = "shotman"
pkgver = "0.4.6"
pkgrel = 0
build_style = "cargo"
hostmakedepends = ["cargo-auditable", "pkgconf", "scdoc"]
makedepends = ["libxkbcommon-devel", "rust-std"]
depends = ["slurp"]
pkgdesc = "Screenshot GUI for Wayland"
maintainer = "triallax <triallax@tutanota.com>"
license = "ISC"
url = "https://sr.ht/~whynothugo/shotman"
source = f"https://git.sr.ht/~whynothugo/shotman/archive/v{pkgver}.tar.gz"
sha256 = "a664dc014850fa15298216dc66cecb99a16de5e3aafe7a5fb347c8fc83d30a6d"
env = {
    "SHOTMAN_VERSION": f"v{pkgver}",
}
# !check because no tests, and !cross because completions are generated by
# running a binary
options = ["!check", "!cross"]


def post_build(self):
    self.do("make", "shotman.1")

    for shell in ["bash", "zsh", "fish"]:
        with open(self.cwd / f"shotman.{shell}", "w") as cf:
            self.do(
                f"target/{self.profile().triplet}/release/shotman_completions",
                shell,
                stdout=cf,
            )


def post_install(self):
    self.install_license("LICENCE.md")
    self.install_man("shotman.1")

    self.install_completion("shotman.bash", "bash")
    self.install_completion("shotman.zsh", "zsh")
    self.install_completion("shotman.fish", "fish")
