pkgname = "base-removed-dbg"
pkgver = "1.0"
pkgrel = 10
build_style = "meta"
provides = []
pkgdesc = "Removed debug packages"
license = "custom:meta"
url = "https://chimera-linux.org"
options = ["empty"]

for _pkg in [
    "alsa-pipewire",
    "bsatool",
    "debuginfod",
    "debuginfod-libs",
    "device-mapper",
    "dmesg",
    "esmtool",
    "fcitx5-gtk3",
    "fcitx5-gtk4",
    "fdisk",
    "fstrim",
    "fuse2fs",
    "gmpxx",
    "gstreamer-libcamera",
    "gstreamer-pipewire",
    "heif-thumbnailer",
    "irqtop",
    "libasn1",
    "libblkid",
    "libbluetooth",
    "libbtrfs",
    "libbtrfsutil",
    "libbzip3",
    "libcdparanoia",
    "libcolord",
    "libcryptsetup",
    "libdjvulibre",
    "libecpg",
    "libefivar",
    "libelogind",
    "libfdisk",
    "libflac",
    "libgdm",
    "libgirepository",
    "libglycin",
    "libglycin-gtk4",
    "libgs",
    "libgssapi",
    "libhcrypto",
    "libhdb",
    "libheimbase",
    "libheimntlm",
    "libhx509",
    "libibus",
    "libiptc",
    "libkadm5clnt",
    "libkadm5srv",
    "libkafs",
    "libkdc",
    "libkrb5",
    "libldns",
    "libltdl",
    "libmagic",
    "libmagick",
    "libmagick-perl",
    "libmount",
    "libnftables",
    "libnm",
    "libnss_winbind",
    "libntfs-3g",
    "libnuma",
    "libpcre2",
    "libpkgconf",
    "libplist++",
    "libpoppler-cpp",
    "libpoppler-glib",
    "libpoppler-qt6",
    "libpq",
    "libpytalloc-util",
    "libroken",
    "librtmp",
    "libsane",
    "libsensors",
    "libsl",
    "libsmartcols",
    "libsmbclient",
    "libspirv-tools-shared",
    "libsquashfs",
    "libsysfs",
    "libtotem-plparser-mini",
    "libtspi",
    "libunbound",
    "libuuid",
    "libuuid-progs",
    "libvala",
    "libvaladoc",
    "libwbclient",
    "libwget",
    "libwind",
    "libwoff2common",
    "libwoff2dec",
    "libwoff2enc",
    "libxtables",
    "lidb-progs",
    "lscpu",
    "mkfs",
    "mount",
    "nfs-server",
    "pam_cgroup",
    "pam_elogind",
    "pam_winbind",
    "projucer",
    "python-opencolorio",
    "python-openimageio",
    "python-openvdb",
    "rename",
    "rfkill",
    "runuser",
    "sdl",
    "tzutils",
    "valadoc",
    "xmlwf",
    "xsltproc",
    "zramctl",
]:
    provides += [f"{_pkg}-dbg=9999"]
