d /run/frr              0750 _frr _frr -
Z /usr/share/frr/conf/* 0640 _frr _frr
z /usr/share/frr/conf   0750 _frr _frr
d /var/lib/frr          0750 _frr _frr -
d /var/log/frr          0750 _frr _frr -
d /var/tmp/frr          0750 _frr _frr -
