if filereadable("/etc/vim/vimrc")
  " system override copy (our defaults replaced)
  source /etc/vim/vimrc
else

" some sane defaults when not overridden
set nocompatible        " Use Vim defaults (much better!)
set bs=2                " Allow backspacing over everything in insert mode
set ai                  " Always set auto-indenting on
set history=50          " keep 50 lines of command history
set ruler               " Show the cursor position all the time

" Don't use Ex mode, use Q for formatting
map Q gq

" When doing tab completion, give the following files lower priority.
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

set nomodeline
syntax on

if filereadable("/etc/vim/vimrc.local")
  " system non-override vimrc (our defaults preserved)
  source /etc/vim/vimrc.local
endif

endif
