#!/bin/sh
# Usage: iptables-start [-6]

iptables=iptables

if [ "$1" = "-6" ]; then
    iptables=ip6tables
fi
if [ ! -e "/etc/iptables/${iptables}.rules" ]; then
    exit 0
fi

/usr/bin/${iptables}-restore -w 3 /etc/iptables/${iptables}.rules
