pkgname = "bsdgrep"
version = "1.0.3"
revision = 1
wrksrc = f"bsdgrep-{version}"
bootstrap = True
build_style = "gnu_makefile"
makedepends = ["bzip2-devel", "zlib-devel", "musl-fts-devel"]
short_desc = "FreeBSD grep(1)"
maintainer = "q66 <q66@chimera-linux.org>"
license = "BSD-2-Clause"
homepage = "https://github.com/chimera-linux/bsdgrep"
distfiles = [f"https://github.com/chimera-linux/bsdgrep/archive/refs/tags/v{version}.tar.gz"]
checksum = ["b7f987508153b309ba629af4b977b491f04cdf57fdaad22228fdc5ab9b5e7900"]
