pkgname = "bubblewrap"
pkgver = "0.6.1"
pkgrel = 0
build_style = "gnu_configure"
make_check_args = ["-j1"]
hostmakedepends = ["pkgconf", "xsltproc", "docbook-xsl-nons"]
makedepends = ["libcap-devel"]
checkdepends = ["bash", "libcap-progs"]
pkgdesc = "Unprivileged sandboxing tool"
maintainer = "q66 <daniel@octaforge.org>"
license = "LGPL-2.0-or-later"
url = "https://github.com/containers/bubblewrap"
source = f"https://github.com/containers/{pkgname}/releases/download/v{pkgver}/{pkgname}-{pkgver}.tar.xz"
sha256 = "9609c7dc162bc68abc29abfab566934fdca37520a15ed01b675adcf3a4303282"
tool_flags = {"CFLAGS": ["-Wno-error,-Wformat-nonliteral"]}
