pkgname = "webp-pixbuf-loader"
pkgver = "0.2.6"
pkgrel = 0
build_style = "meson"
hostmakedepends = ["meson", "pkgconf"]
makedepends = ["gdk-pixbuf-devel", "libwebp-devel"]
pkgdesc = "WebP image format GdkPixbuf loader"
maintainer = "GeopJr <evan@geopjr.dev>"
license = "LGPL-2.0-or-later"
url = "https://github.com/aruiz/webp-pixbuf-loader"
source = f"{url}/archive/refs/tags/{pkgver}.tar.gz"
sha256 = "8d6db7f8a95df7649dccb9cfff1b922793427c0d59bc4d07723e3ba4c9e9832d"
