--- a/makefile
+++ b/makefile
@@ -1,5 +1,5 @@
 LIBNAME = lpeg
-LUADIR = ./lua/
+LUADIR = /usr/include/lua5.5
 
 COPT = -O2 -DNDEBUG
 # COPT = -O0 -DLPEG_DEBUG -g
@@ -26,7 +26,7 @@
 
 
 CFLAGS = $(CWARNS) $(COPT) -std=c99 -I$(LUADIR) -fPIC
-CC = gcc
+CC = clang
 
 FILES = lpvm.o lpcap.o lptree.o lpcode.o lpprint.o lpcset.o
 
@@ -39,7 +39,7 @@
 	$(MAKE) lpeg.so "DLLFLAGS = -bundle -undefined dynamic_lookup"
 
 lpeg.so: $(FILES)
-	env $(CC) $(DLLFLAGS) $(FILES) -o lpeg.so
+	$(CC) -shared $(CFLAGS) $(LDFLAGS) $(FILES) -o lpeg.so
 
 $(FILES): makefile
 
