#!/bin/sh

case "$1" in
    start) exec /usr/lib/udevd --daemon ;;
    stop) /usr/bin/udevadm control -e; exit 0 ;;
    settle) exec /usr/bin/udevadm settle ;;
    trigger) exec /usr/bin/udevadm trigger --action=add ;;
esac

echo "unknown action: $1"
exit 1
